/* 
 * File:   main.cpp
 * Author: Nicholas Mwangi
 * Created on March 18, 2015, 11:27  AM
 *      Purpose: Stadium Seating
 */

//System Libraries

#include <iostream>//I/O standard
#include <iomanip>//Formatting
#include <fstream>//I/O File
using namespace std;

//User Libraries

//Global Constants

//Function Prototypes

//Execution Begins Here!
 
int main(int argc, char**argv) {
    // Declare variables
    
    unsigned short classA; //cost of class A tickets
    unsigned short classB; //cost of class B tickets
    unsigned short classC; //cost of class C tickets
    
    float income; //income generated by sales
    
    unsigned short ticketA;
    unsigned short ticketB;
    unsigned short ticketC;
   
    classA = 15;
    classB = 12;
    classC = 9;
   
    
    //Prompt the user for inputs
    cout<< "How many class A tickets were sold?"<<endl;
    cin>> ticketA;
    cout<< "How many class B tickets were sold?"<<endl;
    cin>> ticketB;
    cout<< "How many class C tickets were sold?"<< endl;
    cin >> ticketC;
    
    
    //calculate Class A ticket sales
    
    income = (classA * ticketA)+(classB * ticketB)+(classC * ticketC) ;
    
    cout<<setprecision(2)<<fixed<<"Income generated from all ticket sales is $ "<< income << endl;
   
    return 0;
}


