/*
 * File: welcome.cc
 * Author: Nicholas Mwangi
 * 
 * Created on March 10, 2015, 4:45 PM
 * Purpose: To calculate the amount generated by East Coast sales Division
 * 
 */

//System Libraries

#include <iostream>

using namespace std;

//User Libraries

//Global constants

//Execution begins here!!

int main(int argc, char**argv) {
    
    //Declare variables
    //sales for entire East coast division is $4.6 million
    //Sales for sales division is 62% of total sales
    
    float totlsal;
    float sales;
    
    
    totlsal=4600000;
    
    sales=0.62;
    
    
    // calculate and display 62% of $4,600,000 which
    //is the amount generated from sales division
   
     
    float saleval= sales*totlsal;
    cout << saleval << endl;
    
    
    return 0;
}
